### ISSUE TITLE
codespace":"sdk","code":4,"message":"signature verification failed

### ISSUE THREAD

**Issue by wjdfx** [hashgard/hashgard#24]
hashgardcli bank broadcast sign.json -o=json --indent --chain-id=sif-3001
{
 "height": "0",
 "txhash": "C26494BED5A0E7CD05FF9CE141A259B5AFAB8A1C9D2E19C81D41DA381AD2CC9C"
}
ERROR: {"codespace":"sdk","code":4,"message":"signature verification failed"}

Command:

hashgard_0.3.2-linux_amd64/hashgardcli keys add a1
hashgard_0.3.2-linux_amd64/hashgardcli keys add a2
hashgard_0.3.2-linux_amd64/hashgardcli keys add a3

hashgardcli keys add a123 --multisig=a1,a2,a3 --multisig-threshold=2

hashgardcli keys show a123 -o=text

NAME:	TYPE:	ADDRESS:						PUBKEY:
a123	offline	gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq	gardpub1ytql0csgqgfzd666axrjzqjp6c0w038d5va4ce3efnhjj55ukn5ykc08t600hesjq05djqqtfufzd666axrjzqcu5j9suejwddcv4rj2qccx2wp0ylnqqe03lgksgrf3f6t53qwaxyfzd666axrjzqcwa8ydc5se0qkl0lfwc5mgf6fnedu5vylgxe3s6efsysawgt9gqqyjzgs9

hashgardcli bank send gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq 10gard --from=bitcat --chain-id=sif-3001

hashgardcli bank send gard1d0s06rave0a6xzvuw7nhz782vcty99hgunc724 1gard --from=a123 --generate-only >unsignedTx.json --chain-id=sif-3001

hashgardcli bank sign unsignedTx.json --multisig=gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq  --name=a1 --output-document=a1sign.json

hashgardcli bank sign unsignedTx.json --multisig=gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq  --name=a2 --output-document=a2sign.json

hashgardcli bank multisign  unsignedTx.json a123 a1sign.json a2sign.json --output-document=sign.json

hashgardcli bank broadcast sign.json -o=json --indent --chain-id=sif-3001

cat a1sign.json
{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"Aw7pyNxSGXgt9/0uxTaE6TPLeUYT6DZjDWUwJDrkLKgA"},"signature":"vwRy+ZlUfxTwR2EwPn9d2UYyhidGZhBfjo5BAoOfsAcQDEfFvxoc+WNTj56U88Np/wQetD5tiFjYBT6QD6DKrA=="}

cat a2sign.json
{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"AkHWHufE7aM7XGY5TO8pUpy06Eth516e++YSA+jZAAtP"},"signature":"NBiZ4moAN1bkX+/C26ZZgvQb9R2CWmywY7jnhlqj70h6j+HbvUTfoW0jxgza2AMMeraNGnUa1jHP5xUJ51GEBQ=="}

cat sign.json
{"type":"auth/StdTx","value":{"msg":[{"type":"cosmos-sdk/Send","value":{"from_address":"gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq","to_address":"gard1d0s06rave0a6xzvuw7nhz782vcty99hgunc724","amount":[{"denom":"gard","amount":"1"}]}}],"fee":{"amount":null,"gas":"200000"},"signatures":[{"pub_key":{"type":"tendermint/PubKeyMultisigThreshold","value":{"threshold":"2","pubkeys":[{"type":"tendermint/PubKeySecp256k1","value":"AkHWHufE7aM7XGY5TO8pUpy06Eth516e++YSA+jZAAtP"},{"type":"tendermint/PubKeySecp256k1","value":"Axykiw5mTmtwyo5KBjBlOC8n5gBl8fotBA0xTpdIgd0x"},{"type":"tendermint/PubKeySecp256k1","value":"Aw7pyNxSGXgt9/0uxTaE6TPLeUYT6DZjDWUwJDrkLKgA"}]}},"signature":"CgUIAxIBoBJANBiZ4moAN1bkX+/C26ZZgvQb9R2CWmywY7jnhlqj70h6j+HbvUTfoW0jxgza2AMMeraNGnUa1jHP5xUJ51GEBRJAvwRy+ZlUfxTwR2EwPn9d2UYyhidGZhBfjo5BAoOfsAcQDEfFvxoc+WNTj56U88Np/wQetD5tiFjYBT6QD6DKrA=="}],"memo":""}}

 cat unsignedTx.json
{"type":"auth/StdTx","value":{"msg":[{"type":"cosmos-sdk/Send","value":{"from_address":"gard13kgmy5jjvl3m46cj3zsmz2r47yryzcy9gu8jkq","to_address":"gard1d0s06rave0a6xzvuw7nhz782vcty99hgunc724","amount":[{"denom":"gard","amount":"1"}]}}],"fee":{"amount":null,"gas":"200000"},"signatures":null,"memo":""}}

**Comment by hashgard-victor** [comment]
@wjdfx 
请按照issue模版，在[hashagrd/testnet](https://github.com/hashgard/testnets
)上提交该问题
