### ISSUE TITLE
使用 hashgardcli keys add MyKey --recover重置密钥，未输入助记词直接回车时，不提示失败。

### ISSUE THREAD

**Issue by xuchaoyi99** [hashgard/hashgard#49]
## Summary of Bug （缺陷概述）
 
 

xuchaoyi@ubuntu:/mnt/hgfs/share/hashgard-v0.4.0$ ./hashgardcli keys add xuchaoyi --recover
override the existing name xuchaoyi [Y/n]: y
Enter a passphrase to encrypt your key to disk:
Repeat the passphrase:
> Enter your bip39 mnemonic
 
 
NAME:     TYPE:        ADDRESS:                                              PUBKEY:
xuchaoyi  local gard1t2pm49stt4klxwj02fetcxq5jrw3qexav6txv3         gardpub1addwnpepqddr8eyfrs4lnh5mv9wk2p5yeewvuzh4xjxvlvnfwxxywnqww3m5ugfa4qj

## Steps to Reproduce （复现步骤）
 
 

xuchaoyi@ubuntu:/mnt/hgfs/share/hashgard-v0.4.0$ ./hashgardcli keys add xuchaoyi --recover
override the existing name xuchaoyi [Y/n]: y
Enter a passphrase to encrypt your key to disk:
Repeat the passphrase:
> Enter your bip39 mnemonic
 
 
NAME:     TYPE:        ADDRESS:                                              PUBKEY:
xuchaoyi  local gard1t2pm49stt4klxwj02fetcxq5jrw3qexav6txv3         gardpub1addwnpepqddr8eyfrs4lnh5mv9wk2p5yeewvuzh4xjxvlvnfwxxywnqww3m5ugfa4qj
____
#### For Admin Use （管理员专用）
 - [ ] Not duplicate issue
 - [ ] Appropriate labels applied
 - [ ] Appropriate contributors tagged
 - [ ] Contributor assigned/self-assigned

**Comment by yangyanqing** [comment]
此时创建了一个新的助记词，相当于 `hashgardcli keys add foo`

已在 cosmos-sdk 中提交 issue(cosmos/cosmos-sdk#4219) 和 PR(cosmos/cosmos-sdk#4220)
